version: '3.7'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      DATABASE_URL: 'postgresql://postgres:admin@localhost:5432/postgres'

volumes:
  db_data:
    name: postgres
